


name: Sync to Hugging Face hub
on:
  push:
    branches: [master]

  # to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
      - name: Add remote 
        env:
          HF: ${{ secrets.HF }}
        run: git remote add space  https://huggingface.co/spaces/affafgh98/CI-CD__GPT2 
      - name: Push to hub
        env:
          HF: ${{ secrets.HF }}
        run: git push --force  https://huggingface.co/spaces/affafgh98/CI-CD__GPT2  main